package com.ghordrin.bosshealthbar;

import com.google.common.collect.ImmutableSet;
import java.util.Set;
import net.runelite.api.gameval.NpcID;

// Superior slayer monsters, including their death forms. The weekly data check lists new ones.
final class SuperiorIds
{
	private static final Set<Integer> IDS = ImmutableSet.of(
		NpcID.SUPERIOR_CRAWLING_HAND, NpcID.SUPERIOR_CAVE_CRAWLER, NpcID.SUPERIOR_BANSHEE,
		NpcID.SUPERIOR_KOUREND_BANSHEE, NpcID.SUPERIOR_ROCKSLUG, NpcID.SUPERIOR_COCKATRICE, NpcID.SUPERIOR_PYREFIEND,
		NpcID.SUPERIOR_BASILISK, NpcID.SUPERIOR_INFERNAL_MAGE, NpcID.SUPERIOR_BLOODVELD,
		NpcID.SUPERIOR_KOUREND_BLOODVELD, NpcID.SUPERIOR_JELLY, NpcID.SUPERIOR_KOUREND_JELLY,
		NpcID.SUPERIOR_CAVE_HORROR, NpcID.SUPERIOR_ABBERANT_SPECTRE, NpcID.SUPERIOR_KOUREND_SPECTRE,
		NpcID.SUPERIOR_DUSTDEVIL, NpcID.SUPERIOR_KURASK, NpcID.SUPERIOR_SMOKE_DEVIL, NpcID.SUPERIOR_GARGOYLE,
		NpcID.SUPERIOR_GARGOYLE_DEAD, NpcID.SUPERIOR_DARK_BEAST, NpcID.SUPERIOR_ABYSSAL_DEMON,
		NpcID.SUPERIOR_NECHRYAEL, NpcID.SUPERIOR_BASILISK_KNIGHT, NpcID.SUPERIOR_PYRELORD, NpcID.SUPERIOR_TUROTH,
		NpcID.SUPERIOR_WYRM_DARK, NpcID.SUPERIOR_WYRM_LIGHT, NpcID.SUPERIOR_DRAKE, NpcID.SUPERIOR_DRAKE_DEATH,
		NpcID.SUPERIOR_HYDRA, NpcID.SUPERIOR_WARPED_TERRORBIRD, NpcID.SUPERIOR_WARPED_TORTOISE,
		NpcID.SUPERIOR_ARAXYTE, NpcID.SUPERIOR_CAVE_CRAWLER_ICE, NpcID.SUPERIOR_CUSTODIAN, NpcID.SUPERIOR_GRYPHON,
		NpcID.SUPERIOR_CHILLED_JELLY, NpcID.SUPERIOR_AQUANITE, NpcID.SUPERIOR_AQUANITE_NOLURE,
		NpcID.SUPERIOR_LAVA_STRYKEWYRM, NpcID.SUPERIOR_VENATOR,
		NpcID.DEADMAN_BREACH_SUPERIOR_ABYSSAL_DEMON, NpcID.DEADMAN_BREACH_SUPERIOR_PYREFIEND,
		NpcID.DEADMAN_BREACH_SUPERIOR_CAVE_HORROR, NpcID.DEADMAN_BREACH_SUPERIOR_INFERNAL_MAGE,
		NpcID.DEADMAN_BREACH_SUPERIOR_KOUREND_JELLY, NpcID.DEADMAN_BREACH_SUPERIOR_DARK_BEAST,
		NpcID.LEAGUE_SUPERIOR_CRAWLING_HAND, NpcID.LEAGUE_SUPERIOR_CAVE_CRAWLER, NpcID.LEAGUE_SUPERIOR_BANSHEE,
		NpcID.LEAGUE_SUPERIOR_KOUREND_BANSHEE, NpcID.LEAGUE_SUPERIOR_ROCKSLUG, NpcID.LEAGUE_SUPERIOR_COCKATRICE,
		NpcID.LEAGUE_SUPERIOR_PYREFIEND, NpcID.LEAGUE_SUPERIOR_PYRELORD, NpcID.LEAGUE_SUPERIOR_BASILISK,
		NpcID.LEAGUE_SUPERIOR_BASILISK_KNIGHT, NpcID.LEAGUE_SUPERIOR_INFERNAL_MAGE, NpcID.LEAGUE_SUPERIOR_BLOODVELD,
		NpcID.LEAGUE_SUPERIOR_KOUREND_BLOODVELD, NpcID.LEAGUE_SUPERIOR_JELLY, NpcID.LEAGUE_SUPERIOR_KOUREND_JELLY,
		NpcID.LEAGUE_SUPERIOR_CAVE_HORROR, NpcID.LEAGUE_SUPERIOR_ABBERANT_SPECTRE,
		NpcID.LEAGUE_SUPERIOR_KOUREND_SPECTRE, NpcID.LEAGUE_SUPERIOR_DUSTDEVIL, NpcID.LEAGUE_SUPERIOR_KURASK,
		NpcID.LEAGUE_SUPERIOR_SMOKE_DEVIL, NpcID.LEAGUE_SUPERIOR_GARGOYLE, NpcID.LEAGUE_SUPERIOR_GARGOYLE_DEAD,
		NpcID.LEAGUE_SUPERIOR_DARK_BEAST, NpcID.LEAGUE_SUPERIOR_ABYSSAL_DEMON, NpcID.LEAGUE_SUPERIOR_NECHRYAEL,
		NpcID.LEAGUE_SUPERIOR_TUROTH, NpcID.LEAGUE_SUPERIOR_WYRM_DARK, NpcID.LEAGUE_SUPERIOR_WYRM_LIGHT,
		NpcID.LEAGUE_SUPERIOR_DRAKE, NpcID.LEAGUE_SUPERIOR_DRAKE_DEATH, NpcID.LEAGUE_SUPERIOR_HYDRA);

	private SuperiorIds()
	{
	}

	static boolean contains(int npcId)
	{
		return IDS.contains(npcId);
	}
}
